import {readFile} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const text=await readFile(resolve(root,'SKILL.md'),'utf8');
const frontmatter=/^---\r?\n([\s\S]*?)\r?\n---/.exec(text)?.[1];
const name=/^name:\s*([a-z0-9-]+)\s*$/m.exec(frontmatter??'')?.[1];
const description=/^description:\s*(\S.*)$/m.exec(frontmatter??'')?.[1];
const version=/^\s{2}version:\s*(\d+\.\d+\.\d+)\s*$/m.exec(frontmatter??'')?.[1];
if(name!=='oversoul'||name.length>64||!description||version!=='0.1.0'||/TODO|\[INSERT/.test(text))throw new Error('Invalid skill frontmatter, version, or unfinished scaffold');
await readFile(resolve(root,'scripts/linked-repo.mjs'));
console.log('Oversoul YAML frontmatter, version 0.1.0, name, description, and client reference validated.');
